version: "3.9"

services:
  db:
    image: postgres
    container_name: fsw-donalds
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Porta padrão do PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080" # Adminer rodará na porta 8080 para gerenciar o banco

volumes:
  postgres_data:
    driver: local
